name: Test Github Actions

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-date:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set current date
      run: echo "CURRENT_DATE=$(date -u +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Create/update date.txt
      run: echo "$CURRENT_DATE" > date.txt

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add date.txt
        git commit -m "Update date.txt with $CURRENT_DATE" || echo "No changes to commit"
        git push
